# Sample rates
# Sample rate of a disabled sensor
BSEC_SAMPLE_RATE_DISABLED = 65535.0
# Sample rate in case of Ultra Low Power Mode
BSEC_SAMPLE_RATE_ULP = 0.0033333
# Sample rate in case of Low Power Mode
BSEC_SAMPLE_RATE_LP = 0.33333
# Input value used to trigger an extra measurment (ULP plus)
BSEC_SAMPLE_RATE_ULP_MEASUREMENT_ON_DEMAND = 0.0
BSEC_SAMPLE_RATE_HIGH_PERFORMANCE = 0.055556


# BSEC max
BSEC_MAX_WORKBUFFER_SIZE = 4096
BSEC_MAX_PHYSICAL_SENSOR = 8
BSEC_MAX_PROPERTY_BLOB_SIZE = 2277
BSEC_MAX_STATE_BLOB_SIZE = 197


# Measurement Value ranges
# Min value for IAQ
BSEC_MIN_IAQ = 0
# Max value for IAQ
BSEC_MAX_IAQ = 500


# BSEC Outputs
BSEC_OUTPUT_IAQ = 1
BSEC_OUTPUT_STATIC_IAQ = 2
BSEC_OUTPUT_CO2_EQUIVALENT = 3
BSEC_OUTPUT_BREATH_VOC_EQUIVALENT = 4
BSEC_OUTPUT_RAW_TEMEPERATURE = 6
BSEC_OUTPUT_RAW_PRESSURE = 7
BSEC_OUTPUT_RAW_HUMIDITY = 8
BSEC_OUTPUT_RAW_GAS = 9
BSEC_OUTPUT_STABILIZATION_STATUS = 12
BSEC_OUTPUT_RUN_IN_STATUS = 13
BSEC_OUTPUT_SENSOR_HEAT_COMPENSATED_TEMPERATURE = 14
BSEC_OUTPUT_SENSOR_HEAT_COMPENSATED_HUMIDITY = 15
BSEC_OUTPUT_COMPENSATED_GAS = 18
BSEC_OUTPUT_GAS_PERCENTAGE = 21
BSEC_OUTPUT_GAS_ESTIMATE_1 = 22
BSEC_OUTPUT_GAS_ESTIMATE_2 = 23
BSEC_OUTPUT_GAS_ESTIMATE_3 = 24
BSEC_OUTPUT_GAS_ESTIMATE_4 = 25
BSEC_OUTPUT_RAW_GAS_INDEX = 26